### ISSUE TITLE
Executable fails

### ISSUE THREAD

**Issue by ips-james** [gideonn/insta-Unfollow-Users#8]
####################################
                ####################################
                ####### Insta User Unfollower ######
                ####################################
                # Developed by Abhishek Srivastava #
                ####################################
                ####################################

Token found...
Started Un-following
Traceback (most recent call last):
  File "<string>", line 132, in <module>
  File "<string>", line 45, in core
KeyError: 'data'
instaUnfollower returned -1

**Comment by gideonn** [comment]
This fails because Instagram changed its API behavior. I have added a note in README so that it doesn't confuse people. 

Thanks for opening the issue though! I will work on the fix when I get time.

Feel free to try out Instagram Gallery Downloader though, according to the new API policies, you can only access your own data.
